apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - env:
            - name: AMQP_URL
              value: amqp://rabbit-mq?connection_attempts=10&retry_delay=10
          image: consumer
          name: consumer
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/consumer
              name: consumer-claim0
      restartPolicy: Always
      volumes:
        - name: consumer-claim0
          persistentVolumeClaim:
            claimName: consumer-claim0
status: {}
