version: "3"

# list of containers to be run
services:

  # rabbit_mq container uses the default rabbitmq image
  # exposes the ports
  # uses the specified volume
  rabbit-mq:

    # we use management image to get the
    # plugin for web dashboard
    image: rabbitmq:3.8-rc-management
    container_name: rabbit-mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit-mqdata:/usr/share/rabbitmq/data

  # produces container builds the producer image
  # and produces message to the queue
  producer:
    build: producer
    depends_on:
        - rabbit-mq
    ports:
        - '5000'
    environment:
        AMQP_URL: 'amqp://rabbit-mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer

  # consumer container builds the consumer image
  # and consumes messages from the queue
  # we spawn 2 consumer containers to run parallely
  # on the same queue
  consumer:
    build: consumer
    depends_on:
        - rabbit-mq
    ports:
        - '5001'
    environment:
        AMQP_URL: 'amqp://rabbit-mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
  consumerm:
    build: consumerMath
    depends_on:
        - rabbit-mq
    ports:
        - '5002'
    environment:
        AMQP_URL: 'amqp://rabbit-mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumerMath:/usr/src/app/consumerMath
volumes:
    rabbit-mqdata:
      driver: local
