version: "3"

# list of containers to be run
services:

  # rabbit_mq container uses the default rabbitmq image
  # exposes the ports
  # uses the specified volume
  rabbit-mq:

    # we use management image to get the
    # plugin for web dashboard
    image: rabbitmq:3.8-rc-management
    container_name: rabbit-mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit-mqdata:/usr/share/rabbitmq/data

  consumer:
    build: consumer
    depends_on:
        - rabbit-mq
    environment:
        AMQP_URL: 'amqp://rabbit-mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
volumes:
    rabbit-mqdata:
      driver: local
